---
name: Checkov
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          skip_check: CKV_AWS_35, CKV_AWS_145, CKV_AWS_144, CKV2_AWS_10, CKV_AWS_252, CKV_AWS_18, CKV_AWS_300, CKV2_AWS_3, CKV2_AWS_62